// Mocks generated by Mockito 5.4.6 from annotations
// in flowrist/test/features/auth/domain/use_cases/register_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowrist/config/base_response/base_response.dart' as _i4;
import 'package:flowrist/features/auth/data/models/register_request_dto.dart'
    as _i6;
import 'package:flowrist/features/auth/domain/entities/login_entity.dart'
    as _i8;
import 'package:flowrist/features/auth/domain/entities/user_entity.dart' as _i5;
import 'package:flowrist/features/auth/domain/params/login_params.dart' as _i9;
import 'package:flowrist/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UserEntity>> register(
    _i6.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.UserEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.UserEntity>>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UserEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.LoginEntity>> login(
    _i9.LoginParams? params,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params, rememberMe]),
            returnValue: _i3.Future<_i4.BaseResponse<_i8.LoginEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i8.LoginEntity>>(
                this,
                Invocation.method(#login, [params, rememberMe]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.LoginEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<void>> forgotPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i3.Future<_i4.BaseResponse<void>>.value(
              _i7.dummyValue<_i4.BaseResponse<void>>(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<void>>);

  @override
  _i3.Future<_i4.BaseResponse<Map<String, dynamic>>> verifyOtp({
    required String? email,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#email: email, #otp: otp}),
            returnValue:
                _i3.Future<_i4.BaseResponse<Map<String, dynamic>>>.value(
                  _i7.dummyValue<_i4.BaseResponse<Map<String, dynamic>>>(
                    this,
                    Invocation.method(#verifyOtp, [], {
                      #email: email,
                      #otp: otp,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.BaseResponse<void>> resetPassword({
    required String? otpToken,
    required String? password,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #otpToken: otpToken,
              #password: password,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<void>>.value(
              _i7.dummyValue<_i4.BaseResponse<void>>(
                this,
                Invocation.method(#resetPassword, [], {
                  #otpToken: otpToken,
                  #password: password,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<void>>);
}
