// Mocks generated by Mockito 5.4.6 from annotations
// in flowrist/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flowrist/config/session/session_service.dart' as _i11;
import 'package:flowrist/features/auth/data/data_sources/contract/remote/auth_remote_data_source.dart'
    as _i7;
import 'package:flowrist/features/auth/data/models/forget_password_response_dto.dart'
    as _i4;
import 'package:flowrist/features/auth/data/models/login_response.dart' as _i3;
import 'package:flowrist/features/auth/data/models/register_request_dto.dart'
    as _i9;
import 'package:flowrist/features/auth/data/models/register_response_dto.dart'
    as _i2;
import 'package:flowrist/features/auth/data/models/reset_password_response_dto.dart'
    as _i6;
import 'package:flowrist/features/auth/data/models/verify_otp_response_dto.dart'
    as _i5;
import 'package:flowrist/features/auth/data/request/login_request.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyOtpResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyOtpResponseDto {
  _FakeVerifyOtpResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i7.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.RegisterResponseDto> register(
    _i9.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i8.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.RegisterResponseDto>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.ForgetPasswordResponseDto> forgotPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i8.Future<_i4.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_2(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i8.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i8.Future<_i5.VerifyOtpResponseDto> verifyOtp({
    required String? email,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {#email: email, #otp: otp}),
            returnValue: _i8.Future<_i5.VerifyOtpResponseDto>.value(
              _FakeVerifyOtpResponseDto_3(
                this,
                Invocation.method(#verifyOtp, [], {#email: email, #otp: otp}),
              ),
            ),
          )
          as _i8.Future<_i5.VerifyOtpResponseDto>);

  @override
  _i8.Future<_i6.ResetPasswordResponseDto> resetPassword({
    required String? otpToken,
    required String? password,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #otpToken: otpToken,
              #password: password,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i8.Future<_i6.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_4(
                this,
                Invocation.method(#resetPassword, [], {
                  #otpToken: otpToken,
                  #password: password,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.ResetPasswordResponseDto>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i11.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isRemembered() =>
      (super.noSuchMethod(
            Invocation.method(#isRemembered, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setGuestMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGuestMode, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isGuest() =>
      (super.noSuchMethod(
            Invocation.method(#isGuest, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> saveToken(String? token, {bool? rememberMe = false}) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token], {#rememberMe: rememberMe}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
