// Mocks generated by Mockito 5.4.6 from annotations
// in flowrist/test/features/auth/presentation/login/cubit/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowrist/config/base_response/base_response.dart' as _i4;
import 'package:flowrist/config/session/session_service.dart' as _i8;
import 'package:flowrist/features/auth/domain/entities/login_entity.dart'
    as _i5;
import 'package:flowrist/features/auth/domain/params/login_params.dart' as _i6;
import 'package:flowrist/features/auth/domain/use_cases/login_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i2.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.LoginEntity>> call(
    _i6.LoginParams? params,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params, rememberMe]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.LoginEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.LoginEntity>>(
                this,
                Invocation.method(#call, [params, rememberMe]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.LoginEntity>>);
}

/// A class which mocks [SessionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionService extends _i1.Mock implements _i8.SessionService {
  MockSessionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isRemembered() =>
      (super.noSuchMethod(
            Invocation.method(#isRemembered, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setGuestMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGuestMode, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isGuest() =>
      (super.noSuchMethod(
            Invocation.method(#isGuest, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> saveToken(String? token, {bool? rememberMe = false}) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token], {#rememberMe: rememberMe}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
