// Mocks generated by Mockito 5.4.6 from annotations
// in flowrist/test/features/auth/data/data_sources/impl/remote/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flowrist/features/auth/data/client/auth_api_client.dart' as _i7;
import 'package:flowrist/features/auth/data/models/forget_password_request_dto.dart'
    as _i11;
import 'package:flowrist/features/auth/data/models/forget_password_response_dto.dart'
    as _i4;
import 'package:flowrist/features/auth/data/models/login_response.dart' as _i3;
import 'package:flowrist/features/auth/data/models/register_request_dto.dart'
    as _i9;
import 'package:flowrist/features/auth/data/models/register_response_dto.dart'
    as _i2;
import 'package:flowrist/features/auth/data/models/reset_password_request_dto.dart'
    as _i13;
import 'package:flowrist/features/auth/data/models/reset_password_response_dto.dart'
    as _i6;
import 'package:flowrist/features/auth/data/models/verify_otp_request_dto.dart'
    as _i12;
import 'package:flowrist/features/auth/data/models/verify_otp_response_dto.dart'
    as _i5;
import 'package:flowrist/features/auth/data/request/login_request.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyOtpResponseDto_3 extends _i1.SmartFake
    implements _i5.VerifyOtpResponseDto {
  _FakeVerifyOtpResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i7.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.RegisterResponseDto> register(
    _i9.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i8.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.RegisterResponseDto>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.ForgetPasswordResponseDto> forgotPassword(
    _i11.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i8.Future<_i4.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_2(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i8.Future<_i5.VerifyOtpResponseDto> verifyOtp(
    _i12.VerifyOtpRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i8.Future<_i5.VerifyOtpResponseDto>.value(
              _FakeVerifyOtpResponseDto_3(
                this,
                Invocation.method(#verifyOtp, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.VerifyOtpResponseDto>);

  @override
  _i8.Future<_i6.ResetPasswordResponseDto> resetPassword(
    _i13.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i6.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_4(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.ResetPasswordResponseDto>);
}
