name: Lint Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.44.4
      - name: Install packages
        run: flutter pub get
      - name: Run generator
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Run static analysis
        run: flutter analyze